# Generated by Django 4.1.7 on 2023-03-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2001-02-28'),
            preserve_default=False,
        ),
    ]
